NAME = get_next_line

CC = cc
CFLAGS = -Wall -Werror -Wextra
OPTION = -D BUFFER_SIZE=42

SRC = main.c \
      get_next_line.c \
      get_next_line_utils.c

OBJ = $(SRC:.c=.o)

all: $(NAME)

$(NAME): $(OBJ)
	$(CC) $(CFLAGS) $(OPTION) $(OBJ) -o $(NAME)

%.o: %.c
	$(CC) $(CFLAGS) $(OPTION) -c $< -o $@

clean:
	rm -f $(OBJ)

fclean: clean
	rm -f $(NAME)

re: fclean all

.PHONY: all clean fclean re
